import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/assets/styles/globals.css';

import { LIST_MEDIA, LIST_NAVIGATION, LIST_SOCIAL, LOCALES } from '@/libs/mock';
import { LocaleProps } from '@/libs/@types';
import { getDictionary } from '@/libs/utils';

import ContextProvider from '@/store/context';

import Footer from '@/components/layout/Footer';
import Navigation from '@/components/layout/Navigation';

const murecho = localFont({
    src: [
        {
            path: '../../assets/fonts/Murecho/Murecho-Black.woff2',
            weight: '900',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-ExtraBold.woff2',
            weight: '800',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-Bold.woff2',
            weight: '700',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-SemiBold.woff2',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-Medium.woff2',
            weight: '500',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-Regular.woff2',
            weight: '400',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-Light.woff2',
            weight: '300',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-ExtraLight.woff2',
            weight: '200',
        },
        {
            path: '../../assets/fonts/Murecho/Murecho-Thin.woff2',
            weight: '100',
        },
    ],
    variable: '--font-murecho',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export async function generateStaticParams() {
    const path: { lang: string }[] = [];
    if (LOCALES) {
        LOCALES.forEach((item) => {
            path.push({
                lang: item,
            });
        });
    }

    return path;
}

export default async function RootLayout({ children, params }: LayoutProps<'/[lang]'>) {
    const lang = (await params).lang as LocaleProps;
    const dic = await getDictionary(lang);

    return (
        <ContextProvider>
            <html lang={lang}>
                <body className={murecho.variable}>
                    <Navigation
                        media={LIST_MEDIA}
                        items={LIST_NAVIGATION}
                        button={{
                            open: dic.navigation.button.open,
                            close: dic.navigation.button.close,
                        }}
                        activeLocale={lang}
                        locales={LOCALES}
                    />

                    {children}

                    <Footer social={LIST_SOCIAL} />
                </body>
            </html>
        </ContextProvider>
    );
}
